### ISSUE TITLE
Improve a11y

### ISSUE THREAD

**Issue by ai** [ai/easings.net#100]
Google Lighthouse (you can run it in Chrome DevTools) gives only 67% score for Accessibility.

![20200127110913](https://user-images.githubusercontent.com/19343/73205232-773ef000-40f5-11ea-80eb-ca1da897fab5.png)

Of course, footer link contrast is not really deal breaker. But let’s improve this value to looks good.

**Comment by isolovev** [comment]
I agree with you. This is the result of switching to a slightly different color palette. I will Correct the behavior.
