### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by hazarek** [ai/easings.net#121]
1. The Language code link in readme.md is using the insecure http protocol. Why are you giving external link? You can put the language codes markdown table in readme.md. <img width="642" alt="cap" src="https://user-images.githubusercontent.com/36481442/90990129-83b1fb00-e5a7-11ea-9dd5-92f1a1975bcd.png">
  webcache adress;
  http://webcache.googleusercontent.com/search?q=cache:L79OZ-daqVsJ:www.i18nguy.com/unicode/language-identifiers.html

2. dead link in readme.md -> https://docs.github.com/en/send-pull-requests

**Comment by isolovev** [comment]
@ai what do you think about the first question? Do we need this sign to him to take it and maintain it?

**Comment by ai** [comment]
We need some link to all lost of language codes. But it will be nice to find HTTPS link.

**Comment by hazarek** [comment]
lowercase markdown table
https://gist.github.com/hazarek/8bc30060e1b6fd8e581f22a254b07ff5

csv
https://gist.github.com/hazarek/4fcdc5ba7e8f3a7f0835c1b83824783f

|Region Code|Region Name                               |Languages [Format:Tag (language Name, Region Name)]                                                                                                                                                                                                                                                                          |
|-----------|------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|(none)     |No Region Assigned                        |eo *(esperanto)* ia *(interlingua)* ie *(interlingue)* io *(ido)* vo *(volapük)*                                                                                                                                                                                                                                                       |
|ad         |Andorra                                   |ca *(catalan)* fr-ad *(french)*                                                                                                                                                                                                                                                                                                  |
|ae         |United Arab Emirates                      |ar-ae *(arabic)*                                                                                                                                                                                                                                                                                                               |
|af         |Afghanistan                               |fa-af *(persian)* ps *(pushto)* ug *(uighur)* uz-af *(uzbek)*                                                                                                                                                                                                                                                                        |
|ag         |Antigua And Barbuda                       |en-ag *(english)*                                                                                                                                                                                                                                                                                                              |
|ai         |Anguilla                                  |en-ai *(english)*                                                                                                                                                                                                                                                                                                              |
|al         |Albania                                   |sq *(albanian)*                                                                                                                                                                                                                                                                                                                |
|am         |Armenia                                   |hy *(armenian)*                                                                                                                                                                                                                                                                                                                |
|an         |Netherlands Antilles                      |nl-an *(dutch)*                                                                                                                                                                                                                                                                                                                |
|ao         |Angola                                    |kg *(kongo)* kj *(kuanyama)* pt-ao *(portuguese)*                                                                                                                                                                                                                                                                                  |
|ar         |Argentina                                 |cy-ar *(welsh)* es-ar *(spanish)* gn *(guarani)*                                                                                                                                                                                                                                                                                   |
|as         |American Samoa                            |en-as *(english)* sm *(samoan)*                                                                                                                                                                                                                                                                                                  |
|at         |Austria                                   |de-at *(german)* hu *(hungarian)*                                                                                                                                                                                                                                                                                                |
|au         |Australia                                 |en-au *(english)* yi *(yiddish)*                                                                                                                                                                                                                                                                                                 |
|aw         |Aruba                                     |nl-aw *(dutch)*                                                                                                                                                                                                                                                                                                                |
|ax         |Åland Islands                             |sv-ax *(swedish)*                                                                                                                                                                                                                                                                                                              |
|az         |Azerbaijan                                |av *(avaric)* az *(azerbaijani)* az-arab *(azerbaijani)* az-cyrl *(azerbaijani)* az-latn *(azerbaijani)* os *(ossetian)*                                                                                                                                                                                                                 |
|ba         |Bosnia And Herzegovina                    |bs *(bosnian)* hr-ba *(croatian)* sr-ba *(serbian)*                                                                                                                                                                                                                                                                                |
|bb         |Barbados                                  |en-bb *(english)*                                                                                                                                                                                                                                                                                                              |
|bd         |Bangladesh                                |bn-bd *(bengali)*                                                                                                                                                                                                                                                                                                              |
|be         |Belgium                                   |de-be *(german)* en-be *(english)* fr-be *(french)* nl-be *(dutch)* wa *(walloon)* yi *(yiddish)*                                                                                                                                                                                                                                        |
|bf         |Burkina Faso                              |bm *(bambara)* fr-bf *(french)* ha *(hausa)*                                                                                                                                                                                                                                                                                       |
|bg         |Bulgaria                                  |bg *(bulgarian)* cu *(church Slavic)* tr-bg *(turkish)*                                                                                                                                                                                                                                                                            |
|bh         |Bahrain                                   |ar-bh *(arabic)*                                                                                                                                                                                                                                                                                                               |
|bi         |Burundi                                   |fr-bi *(french)* rn *(rundi)*                                                                                                                                                                                                                                                                                                    |
|bj         |Benin                                     |fr-bj *(french)*                                                                                                                                                                                                                                                                                                               |
|bm         |Bermuda                                   |en-bm *(english)*                                                                                                                                                                                                                                                                                                              |
|bn         |Brunei Darussalam                         |en-bn *(english)* ms-bn *(malay)*                                                                                                                                                                                                                                                                                                |
|bo         |Bolivia                                   |ay *(aymara)* es-bo *(spanish)*                                                                                                                                                                                                                                                                                                  |
|br         |Brazil                                    |pt-br *(portuguese)*                                                                                                                                                                                                                                                                                                           |
|bs         |Bahamas                                   |en-bs *(english)*                                                                                                                                                                                                                                                                                                              |
|bt         |Bhutan                                    |dz *(dzongkha)* ne *(nepali)*                                                                                                                                                                                                                                                                                                    |
|bw         |Botswana                                  |en-bw *(english)* sn *(shona)* tn-bw *(tswana)*                                                                                                                                                                                                                                                                                    |
|by         |Belarus                                   |be *(belarusian)* cu *(church Slavic)* yi *(yiddish)*                                                                                                                                                                                                                                                                              |
|bz         |Belize                                    |en-bz *(english)*                                                                                                                                                                                                                                                                                                              |
|ca         |Canada                                    |cr *(cree)* en-ca *(english)* fr-ca *(french)* iu *(inuktitut)* oj *(ojibwa)* yi *(yiddish)*                                                                                                                                                                                                                                             |
|cc         |Cocos *(keeling)* Islands                   |ms-cc *(malay)*                                                                                                                                                                                                                                                                                                                |
|cd         |Congo, The Democratic Republic Of The     |fr-cd *(french)* kg *(kongo)* ln-cd *(lingala)* lu *(luba-katanga)*                                                                                                                                                                                                                                                                  |
|cf         |Central African Republic                  |fr-cf *(french)* sg *(sango)*                                                                                                                                                                                                                                                                                                    |
|cg         |Congo                                     |fr-cg *(french)* kg *(kongo)* ln-cg *(lingala)*                                                                                                                                                                                                                                                                                    |
|ch         |Switzerland                               |de-ch *(german)* fr-ch *(french)* it-ch *(italian)* rm *(raeto-romance)*                                                                                                                                                                                                                                                             |
|ci         |Côte D'ivoire                             |ak *(akan)* bm *(bambara)* fr-ci *(french)*                                                                                                                                                                                                                                                                                        |
|ck         |Cook Islands                              |en-ck *(english)*                                                                                                                                                                                                                                                                                                              |
|cl         |Chile                                     |ay *(aymara)* es-cl *(spanish)*                                                                                                                                                                                                                                                                                                  |
|cm         |Cameroon                                  |en-cm *(english)* fr-cm *(french)*                                                                                                                                                                                                                                                                                               |
|cn         |China                                     |bo *(tibetan)* i-hak *(hakka)* ii *(sichuan Yi)* za *(zhuang)* zh-cn *(chinese)* zh-gan *(chinese)* zh-guoyu *(chinese)* zh-hakka *(chinese)* zh-hans *(chinese)* zh-hans-cn *(chinese)* zh-hant *(chinese)* zh-hant-cn *(chinese)* zh-wuu *(chinese)* zh-xiang *(chinese)* zh-yue *(chinese)*                                                             |
|co         |Colombia                                  |es-co *(spanish)*                                                                                                                                                                                                                                                                                                              |
|cr         |Costa Rica                                |es-cr *(spanish)*                                                                                                                                                                                                                                                                                                              |
|cs         |Serbia And Montenegro                     |cu *(church Slavic)* hu *(hungarian)* sq *(albanian)* sr *(serbian)* sr-cyrl *(serbian)* sr-latn *(serbian)*                                                                                                                                                                                                                             |
|cu         |Cuba                                      |es-cu *(spanish)*                                                                                                                                                                                                                                                                                                              |
|cv         |Cape Verde                                |pt-cv *(portuguese)*                                                                                                                                                                                                                                                                                                           |
|cx         |Christmas Island                          |ms-cc *(malay,cocos *(keeling)* islands)*                                                                                                                                                                                                                                                                                        |
|cy         |Cyprus                                    |el-cy *(greek)* tr-cy *(turkish)*                                                                                                                                                                                                                                                                                                |
|cz         |Czech Republic                            |cs *(czech)*                                                                                                                                                                                                                                                                                                                   |
|de         |Germany                                   |da-de *(danish)* da-de *(danish)* de-1901 *(german)* de-1996 *(german)* de-at-1901 *(german)* de-at-1996 *(german)* de-ch-1901 *(german)* de-ch-1996 *(german)* de-de *(german)* de-de-1901 *(german)* de-de-1996 *(german)* dsb *(lower Sorbian)* fy-de *(frisian)* hsb *(upper Sorbian)* lb *(luxembourgish)* nds *(low German)* wen *(sorbian)* yi *(yiddish)*|
|dj         |Djibouti                                  |aa-dj *(afar)* fr-dj *(french)* so-dj *(somali)*                                                                                                                                                                                                                                                                                   |
|dk         |Denmark                                   |da-dk *(danish)* de-dk *(german)*                                                                                                                                                                                                                                                                                                |
|dm         |Dominica                                  |en-dm *(english)*                                                                                                                                                                                                                                                                                                              |
|do         |Dominican Republic                        |es-do *(spanish)*                                                                                                                                                                                                                                                                                                              |
|dz         |Algeria                                   |ar-dz *(arabic)*                                                                                                                                                                                                                                                                                                               |
|ec         |Ecuador                                   |es-ec *(spanish)*                                                                                                                                                                                                                                                                                                              |
|ee         |Estonia                                   |et *(estonian)* yi *(yiddish)*                                                                                                                                                                                                                                                                                                   |
|eg         |Egypt                                     |ar-eg *(arabic)*                                                                                                                                                                                                                                                                                                               |
|er         |Eritrea                                   |aa-er *(afar)* byn *(blin)* en-er *(english)* gez-er *(geez)* ti-er *(tigrinya)* tig *(tigre)*                                                                                                                                                                                                                                           |
|es         |Spain                                     |an *(aragonese)* ca *(catalan)* es-es *(spanish)* eu *(basque)* gl *(galician)*                                                                                                                                                                                                                                                        |
|et         |Ethiopia                                  |aa-et *(afar)* am *(amharic)* en-et *(english)* gez-et *(geez)* om-et *(oromo)* sid *(sidamo)* so-et *(somali)* ti-et *(tigrinya)* wal *(walamo)*                                                                                                                                                                                              |
|fi         |Finland                                   |fi-fi *(finnish)* smn *(inari Sami)* sv-fi *(swedish)*                                                                                                                                                                                                                                                                             |
|fj         |Fiji                                      |en-fj *(english)* fj *(fijian)*                                                                                                                                                                                                                                                                                                  |
|fk         |Falkland Islands *(malvinas)*               |en-fk *(english)*                                                                                                                                                                                                                                                                                                              |
|fm         |Micronesia, Federated States Of           |en-fm *(english)*                                                                                                                                                                                                                                                                                                              |
|fo         |Faroe Islands                             |da-fo *(danish)* fo *(faroese)*                                                                                                                                                                                                                                                                                                  |
|fr         |France                                    |br *(breton)* co *(corsican)* de-fr *(german)* fr-fr *(french)* oc *(occitan)*                                                                                                                                                                                                                                                         |
|ga         |Gabon                                     |fr-ga *(french)*                                                                                                                                                                                                                                                                                                               |
|gb         |United Kingdom                            |cy-gb *(welsh)* en-boont *(english)* en-gb *(english)* en-gb-oed *(english)* en-scouse *(english)* fr-gb *(french)* ga-gb *(irish)* gd *(gaelic)* gv *(manx)* kw *(cornish)*                                                                                                                                                                     |
|gd         |Grenada                                   |en-gd *(english)*                                                                                                                                                                                                                                                                                                              |
|ge         |Georgia                                   |ab *(abkhazian)* ka *(georgian)* os *(ossetian)*                                                                                                                                                                                                                                                                                   |
|gf         |French Guiana                             |fr-gf *(french)*                                                                                                                                                                                                                                                                                                               |
|gh         |Ghana                                     |ak *(akan)* ee *(ewe)* en-gh *(english)* tw *(twi)*                                                                                                                                                                                                                                                                                  |
|gi         |Gibraltar                                 |en-gi *(english)*                                                                                                                                                                                                                                                                                                              |
|gl         |Greenland                                 |da-gl *(danish)* kl *(kalaallisut)*                                                                                                                                                                                                                                                                                              |
|gm         |Gambia                                    |bm *(bambara)* en-gm *(english)* wo *(wolof)*                                                                                                                                                                                                                                                                                      |
|gn         |Guinea                                    |fr-gn *(french)*                                                                                                                                                                                                                                                                                                               |
|gp         |Guadeloupe                                |fr-gp *(french)*                                                                                                                                                                                                                                                                                                               |
|gq         |Equatorial Guinea                         |es-gq *(spanish)*                                                                                                                                                                                                                                                                                                              |
|gr         |Greece                                    |el-gr *(greek)*                                                                                                                                                                                                                                                                                                                |
|gt         |Guatemala                                 |es-gt *(spanish)*                                                                                                                                                                                                                                                                                                              |
|gu         |Guam                                      |ch-gu *(chamorro)* en-gu *(english)*                                                                                                                                                                                                                                                                                             |
|gw         |Guinea-bissau                             |pt-gw *(portuguese)*                                                                                                                                                                                                                                                                                                           |
|gy         |Guyana                                    |en-gy *(english)*                                                                                                                                                                                                                                                                                                              |
|hk         |Hong Kong                                 |en-hk *(english)* zh-hant *(chinese)* zh-hant-hk *(chinese)* zh-hk *(chinese)*                                                                                                                                                                                                                                                       |
|hn         |Honduras                                  |es-hn *(spanish)*                                                                                                                                                                                                                                                                                                              |
|hr         |Croatia                                   |hr-hr *(croatian)* it-hr *(italian)*                                                                                                                                                                                                                                                                                             |
|ht         |Haiti                                     |fr-ht *(french)* ht *(haitian)*                                                                                                                                                                                                                                                                                                  |
|hu         |Hungary                                   |de-hu *(german)* hu-hu *(hungarian)* sk-hu *(slovak)* sr-hu *(serbian)*                                                                                                                                                                                                                                                              |
|id         |Indonesia                                 |id *(indonesian)* jv *(javanese)* su *(sundanese)*                                                                                                                                                                                                                                                                                 |
|ie         |Ireland                                   |en-ie *(english)* ga-ie *(irish)*                                                                                                                                                                                                                                                                                                |
|il         |Israel                                    |ar-il *(arabic)* en-il *(english)* he *(hebrew)* yi *(yiddish)*                                                                                                                                                                                                                                                                      |
|in         |India                                     |ar-in *(arabic)* as *(assamese)* bh *(bihari)* bn-in *(bengali)* en-in *(english)* gu *(gujarati)* hi *(hindi)* kn *(kannada)* kok *(konkani)* ks *(kashmiri)* ml *(malayalam)* mr *(marathi)* ne *(nepali)* or *(oriya)* pa *(panjabi)* pi *(pali)* sa *(sanskrit)* sd-in *(sindhi)* ta-in *(tamil)* te *(telugu)* ur-in *(urdu)*                                     |
|io         |British Indian Ocean Territory            |en-io *(english)*                                                                                                                                                                                                                                                                                                              |
|iq         |Iraq                                      |ar-iq *(arabic)* ku *(kurdish)*                                                                                                                                                                                                                                                                                                  |
|ir         |Iran, Islamic Republic Of                 |ae *(avestan)* fa-ir *(persian)* ku *(kurdish)*                                                                                                                                                                                                                                                                                    |
|is         |Iceland                                   |is *(icelandic)*                                                                                                                                                                                                                                                                                                               |
|it         |Italy                                     |co *(corsican)* de-it *(german)* fr-it *(french)* it-it *(italian)* sc *(sardinian)*                                                                                                                                                                                                                                                   |
|jm         |Jamaica                                   |en-jm *(english)*                                                                                                                                                                                                                                                                                                              |
|jo         |Jordan                                    |ar-jo *(arabic)*                                                                                                                                                                                                                                                                                                               |
|jp         |Japan                                     |ja *(japanese)*                                                                                                                                                                                                                                                                                                                |
|ke         |Kenya                                     |en-ke *(english)* ki *(kikuyu)* om-ke *(oromo)* so-ke *(somali)* sw-ke *(swahili)*                                                                                                                                                                                                                                                     |
|kg         |Kyrgyzstan                                |ky *(kirghiz)* ug *(uighur)*                                                                                                                                                                                                                                                                                                     |
|kh         |Cambodia                                  |km *(khmer)*                                                                                                                                                                                                                                                                                                                   |
|ki         |Kiribati                                  |en-ki *(english)*                                                                                                                                                                                                                                                                                                              |
|km         |Comoros                                   |fr-km *(french)*                                                                                                                                                                                                                                                                                                               |
|kn         |Saint Kitts And Nevis                     |en-kn *(english)*                                                                                                                                                                                                                                                                                                              |
|kp         |Korea, Democratic People's Republic Of    |ko-kp *(korean)*                                                                                                                                                                                                                                                                                                               |
|kr         |Korea, Republic Of                        |ko-kr *(korean)*                                                                                                                                                                                                                                                                                                               |
|kw         |Kuwait                                    |ar-kw *(arabic)*                                                                                                                                                                                                                                                                                                               |
|ky         |Cayman Islands                            |en-ky *(english)*                                                                                                                                                                                                                                                                                                              |
|kz         |Kazakhstan                                |av *(avaric)* kk *(kazakh)* os *(ossetian)* ug *(uighur)*                                                                                                                                                                                                                                                                            |
|la         |Lao People's Democratic Republic          |lo *(lao)*                                                                                                                                                                                                                                                                                                                     |
|lb         |Lebanon                                   |ar-lb *(arabic)* fr-lb *(french)*                                                                                                                                                                                                                                                                                                |
|lc         |Saint Lucia                               |en-lc *(english)*                                                                                                                                                                                                                                                                                                              |
|li         |Liechtenstein                             |de-li *(german)*                                                                                                                                                                                                                                                                                                               |
|lk         |Sri Lanka                                 |si *(sinhala)*                                                                                                                                                                                                                                                                                                                 |
|lr         |Liberia                                   |en-lr *(english)*                                                                                                                                                                                                                                                                                                              |
|ls         |Lesotho                                   |en-ls *(english)* st *(southern Sotho)* xh *(xhosa)*                                                                                                                                                                                                                                                                               |
|lt         |Lithuania                                 |lt *(lithuanian)* yi *(yiddish)*                                                                                                                                                                                                                                                                                                 |
|lu         |Luxembourg                                |de-lu *(german)* fr-lu *(french)* lb *(luxembourgish)*                                                                                                                                                                                                                                                                             |
|lv         |Latvia                                    |lv *(latvian)* yi *(yiddish)*                                                                                                                                                                                                                                                                                                    |
|ly         |Libyan Arab Jamahiriya                    |ar-ly *(arabic)*                                                                                                                                                                                                                                                                                                               |
|ma         |Morocco                                   |ar-ma *(arabic)*                                                                                                                                                                                                                                                                                                               |
|mc         |Monaco                                    |fr-mc *(french)*                                                                                                                                                                                                                                                                                                               |
|md         |Moldova, Republic Of                      |mo *(moldavian)* ro *(romanian)* tr *(turkish)* uk *(ukrainian)* yi *(yiddish)*                                                                                                                                                                                                                                                        |
|mg         |Madagascar                                |fr-mg *(french)* mg *(malagasy)*                                                                                                                                                                                                                                                                                                 |
|mh         |Marshall Islands                          |en-mh *(english)* mh *(marshallese)*                                                                                                                                                                                                                                                                                             |
|mk         |Macedonia, The Former Yugoslav Republic Of|cu *(church Slavic)* mk *(macedonian)*                                                                                                                                                                                                                                                                                           |
|ml         |Mali                                      |bm *(bambara)* fr-ml *(french)*                                                                                                                                                                                                                                                                                                  |
|mm         |Myanmar                                   |my *(burmese)*                                                                                                                                                                                                                                                                                                                 |
|mn         |Mongolia                                  |mn *(mongolian)*                                                                                                                                                                                                                                                                                                               |
|mo         |Macao                                     |zh-hant *(chinese)* zh-hant-mo *(chinese)* zh-mo *(chinese)*                                                                                                                                                                                                                                                                       |
|mp         |Northern Mariana Islands                  |ch-mp *(chamorro)* en-mp *(english)*                                                                                                                                                                                                                                                                                             |
|mq         |Martinique                                |fr-mq *(french)*                                                                                                                                                                                                                                                                                                               |
|mr         |Mauritania                                |ar-mr *(arabic)* wo *(wolof)*                                                                                                                                                                                                                                                                                                    |
|ms         |Montserrat                                |en-ms *(english)*                                                                                                                                                                                                                                                                                                              |
|mt         |Malta                                     |en-mt *(english)* mt *(maltese)*                                                                                                                                                                                                                                                                                                 |
|mu         |Mauritius                                 |en-mu *(english)*                                                                                                                                                                                                                                                                                                              |
|mv         |Maldives                                  |dv *(divehi)*                                                                                                                                                                                                                                                                                                                  |
|mw         |Malawi                                    |en-mw *(english)* ny *(chichewa)*                                                                                                                                                                                                                                                                                                |
|mx         |Mexico                                    |es-mx *(spanish)*                                                                                                                                                                                                                                                                                                              |
|my         |Malaysia                                  |jv *(javanese)* ms-my *(malay)*                                                                                                                                                                                                                                                                                                  |
|mz         |Mozambique                                |pt-mz *(portuguese)* sn *(shona)*                                                                                                                                                                                                                                                                                                |
|na         |Namibia                                   |en-na *(english)* hz *(herero)* ng *(ndonga)*                                                                                                                                                                                                                                                                                      |
|nc         |New Caledonia                             |fr-nc *(french)*                                                                                                                                                                                                                                                                                                               |
|ne         |Niger                                     |ff-ne *(fulah)* fr-ne *(french)* ha *(hausa)* kr *(kanuri)*                                                                                                                                                                                                                                                                          |
|nf         |Norfolk Island                            |en-nf *(english)*                                                                                                                                                                                                                                                                                                              |
|ng         |Nigeria                                   |en-ng *(english)* ff-ng *(fulah)* ha *(hausa)* ig *(igbo)* kr *(kanuri)* yo *(yoruba)*                                                                                                                                                                                                                                                   |
|ni         |Nicaragua                                 |es-ni *(spanish)*                                                                                                                                                                                                                                                                                                              |
|nl         |Netherlands                               |fy-nl *(frisian)* li *(limburgan)* nl-nl *(dutch)*                                                                                                                                                                                                                                                                                 |
|no         |Norway                                    |nb *(bokmål)* nn *(nynorsk)* no *(norwegian)* no-bok *(norwegian)* no-nyn *(norwegian)*                                                                                                                                                                                                                                                |
|np         |Nepal                                     |ne *(nepali)*                                                                                                                                                                                                                                                                                                                  |
|nr         |Nauru                                     |en-nr *(english)* na *(nauru)*                                                                                                                                                                                                                                                                                                   |
|nu         |Niue                                      |en-nu *(english)*                                                                                                                                                                                                                                                                                                              |
|nz         |New Zealand                               |en-nz *(english)* mi *(maori)*                                                                                                                                                                                                                                                                                                   |
|om         |Oman                                      |ar-om *(arabic)*                                                                                                                                                                                                                                                                                                               |
|pa         |Panama                                    |es-pa *(spanish)*                                                                                                                                                                                                                                                                                                              |
|pe         |Peru                                      |ay *(aymara)* es-pe *(spanish)* qu *(quechua)*                                                                                                                                                                                                                                                                                     |
|pf         |French Polynesia                          |fr-pf *(french)* ty *(tahitian)*                                                                                                                                                                                                                                                                                                 |
|pg         |Papua New Guinea                          |en-pg *(english)* ho *(hiri Motu)*                                                                                                                                                                                                                                                                                               |
|ph         |Philippines                               |en-ph *(english)* tl *(tagalog)*                                                                                                                                                                                                                                                                                                 |
|pk         |Pakistan                                  |en-pk *(english)* sd-pk *(sindhi)* ur-pk *(urdu)*                                                                                                                                                                                                                                                                                  |
|pl         |Poland                                    |de-pl *(german)* pl *(polish)* yi *(yiddish)*                                                                                                                                                                                                                                                                                      |
|pm         |Saint Pierre And Miquelon                 |fr-pm *(french)*                                                                                                                                                                                                                                                                                                               |
|pn         |Pitcairn                                  |en-pn *(english)*                                                                                                                                                                                                                                                                                                              |
|pr         |Puerto Rico                               |en-pr *(english)* es-pr *(spanish)*                                                                                                                                                                                                                                                                                              |
|ps         |Palestinian Territory, Occupied           |ar-ps *(arabic)*                                                                                                                                                                                                                                                                                                               |
|pt         |Portugal                                  |pt-pt *(portuguese)*                                                                                                                                                                                                                                                                                                           |
|pw         |Palau                                     |en-pw *(english)*                                                                                                                                                                                                                                                                                                              |
|py         |Paraguay                                  |es-py *(spanish)* gn *(guarani)*                                                                                                                                                                                                                                                                                                 |
|qa         |Qatar                                     |ar-qa *(arabic)*                                                                                                                                                                                                                                                                                                               |
|re         |Réunion                                   |fr-re *(french)*                                                                                                                                                                                                                                                                                                               |
|ro         |Romania                                   |cu *(church Slavic)* hu *(hungarian)* ro *(romanian)* yi *(yiddish)*                                                                                                                                                                                                                                                                 |
|ru         |Russian Federation                        |av *(avaric)* ba *(bashkir)* ce *(chechen)* cu *(church Slavic)* cv *(chuvash)* kv *(komi)* os *(ossetian)* ru-ru *(russian)* tt *(tatar)* yi *(yiddish)*                                                                                                                                                                                        |
|rw         |Rwanda                                    |en-rw *(english)* fr-rw *(french)* rw *(kinyarwanda)*                                                                                                                                                                                                                                                                              |
|sa         |Saudi Arabia                              |ar-sa *(arabic)*                                                                                                                                                                                                                                                                                                               |
|sb         |Solomon Islands                           |en-sb *(english)*                                                                                                                                                                                                                                                                                                              |
|sc         |Seychelles                                |en-sc *(english)* fr-sc *(french)*                                                                                                                                                                                                                                                                                               |
|sd         |Sudan                                     |ar-sd *(arabic)* din *(dinka)* ha *(hausa)*                                                                                                                                                                                                                                                                                        |
|se         |Sweden                                    |fi-se *(finnish)* se *(northern Sami)* sma *(s. Sami)* sme *(n. Sami)* sv-se *(swedish)*                                                                                                                                                                                                                                               |
|sg         |Singapore                                 |bn-sg *(bengali)* en-sg *(english)* ms-sg *(malay)* ta-sg *(tamil)* zh-hans-sg *(chinese)* zh-sg *(chinese)*                                                                                                                                                                                                                             |
|sh         |Saint Helena                              |en-sh *(english)*                                                                                                                                                                                                                                                                                                              |
|si         |Slovenia                                  |hu-si *(hungarian)* it-si *(italian)*                                                                                                                                                                                                                                                                                            |
|sk         |Slovakia                                  |hu *(hungarian)* sk *(slovak)*                                                                                                                                                                                                                                                                                                   |
|sl         |Sierra Leone                              |en-sl *(english)*                                                                                                                                                                                                                                                                                                              |
|sm         |San Marino                                |it-sm *(italian)*                                                                                                                                                                                                                                                                                                              |
|sn         |Senegal                                   |ff-sn *(fulah)* wo *(wolof)*                                                                                                                                                                                                                                                                                                     |
|so         |Somalia                                   |ar-so *(arabic)* en-so *(english)* so-so *(somali)*                                                                                                                                                                                                                                                                                |
|sr         |Suriname                                  |jv *(javanese)* nl-sr *(dutch)*                                                                                                                                                                                                                                                                                                  |
|st         |Sao Tome And Principe                     |pt-st *(portuguese)*                                                                                                                                                                                                                                                                                                           |
|sv         |El Salvador                               |es-sv *(spanish)*                                                                                                                                                                                                                                                                                                              |
|sy         |Syrian Arab Republic                      |ar-sy *(arabic)* syr *(syriac)*                                                                                                                                                                                                                                                                                                  |
|sz         |Swaziland                                 |en-sz *(english)* ss-sz *(swati)*                                                                                                                                                                                                                                                                                                |
|tc         |Turks And Caicos Islands                  |en-tc *(english)*                                                                                                                                                                                                                                                                                                              |
|td         |Chad                                      |ar-td *(arabic)* fr-td *(french)*                                                                                                                                                                                                                                                                                                |
|tg         |Togo                                      |ee *(ewe)* fr-tg *(french)* ha *(hausa)*                                                                                                                                                                                                                                                                                           |
|th         |Thailand                                  |si *(sinhala)* th *(thai)*                                                                                                                                                                                                                                                                                                       |
|tj         |Tajikistan                                |os *(ossetian)* tg *(tajik)* ug *(uighur)*                                                                                                                                                                                                                                                                                         |
|tk         |Tokelau                                   |en-tk *(english)*                                                                                                                                                                                                                                                                                                              |
|tl         |Timor-leste                               |pt-tl *(portuguese)*                                                                                                                                                                                                                                                                                                           |
|tm         |Turkmenistan                              |os *(ossetian)* tk *(turkmen)*                                                                                                                                                                                                                                                                                                   |
|tn         |Tunisia                                   |ar-tn *(arabic)*                                                                                                                                                                                                                                                                                                               |
|to         |Tonga                                     |en-to *(english)* to *(tongan)*                                                                                                                                                                                                                                                                                                  |
|tr         |Turkey                                    |ab *(abkhazian)* av *(avaric)* ku *(kurdish)* tr-tr *(turkish)* ug *(uighur)*                                                                                                                                                                                                                                                          |
|tt         |Trinidad And Tobago                       |en-tt *(english)*                                                                                                                                                                                                                                                                                                              |
|tv         |Tuvalu                                    |gil *(gilbertese)* tvl *(tuvalu)*                                                                                                                                                                                                                                                                                                |
|tw         |Taiwan, Province Of China                 |zh-hant *(chinese)* zh-hant-tw *(chinese)* zh-min *(chinese)* zh-min-nan *(chinese)* zh-tw *(chinese)*                                                                                                                                                                                                                                 |
|tz         |Tanzania, United Republic Of              |sw-tz *(swahili)*                                                                                                                                                                                                                                                                                                              |
|ua         |Ukraine                                   |ab *(abkhazian)* cu *(church Slavic)* hu *(hungarian)* os *(ossetian)* pl *(polish)* ro *(romanian)* ru-ua *(russian)* uk *(ukrainian)* yi *(yiddish)*                                                                                                                                                                                         |
|ug         |Uganda                                    |en-ug *(english)* lg *(ganda)*                                                                                                                                                                                                                                                                                                   |
|um         |United States Minor Outlying Islands      |en-um *(english)*                                                                                                                                                                                                                                                                                                              |
|us         |United States                             |en-us *(english)* es-us *(spanish)* haw *(hawaiian)* ik *(inupiaq)* nv *(navajo)* oj *(ojibwa)* yi *(yiddish)*                                                                                                                                                                                                                             |
|uy         |Uruguay                                   |es-uy *(spanish)*                                                                                                                                                                                                                                                                                                              |
|uz         |Uzbekistan                                |os *(ossetian)* ug *(uighur)* uz-cyrl *(uzbek)* uz-latn *(uzbek)* uz-uz *(uzbek)*                                                                                                                                                                                                                                                      |
|va         |Holy See *(vatican City State)*             |fr *(french)* it *(italian)* la *(latin)*                                                                                                                                                                                                                                                                                          |
|vc         |Saint Vincent And The Grenadines          |en-vc *(english)*                                                                                                                                                                                                                                                                                                              |
|ve         |Venezuela                                 |es-ve *(spanish)*                                                                                                                                                                                                                                                                                                              |
|vg         |Virgin Islands, British                   |en-vg *(english)*                                                                                                                                                                                                                                                                                                              |
|vi         |Virgin Islands, U.s.                      |en-vi *(english)*                                                                                                                                                                                                                                                                                                              |
|vn         |Viet Nam                                  |vi *(vietnamese)*                                                                                                                                                                                                                                                                                                              |
|vu         |Vanuatu                                   |bi *(bislama)* en-vu *(english)* fr-vu *(french)*                                                                                                                                                                                                                                                                                  |
|wf         |Wallis And Futuna                         |fr-wf *(french)*                                                                                                                                                                                                                                                                                                               |
|ws         |Samoa                                     |en-ws *(english)* sm *(samoan)*                                                                                                                                                                                                                                                                                                  |
|ye         |Yemen                                     |ar-ye *(arabic)*                                                                                                                                                                                                                                                                                                               |
|yt         |Mayotte                                   |fr-yt *(french)*                                                                                                                                                                                                                                                                                                               |
|yu         |Yugoslavia                                |sr-cyrl-yu *(serbian)* sr-latn-yu *(serbian)* sr-yu *(serbian)*                                                                                                                                                                                                                                                                    |
|za         |South Africa                              |af *(afrikaans)* en-za *(english)* nr *(s. Ndebele)* ss-za *(swati)* tn-za *(tswana)* ts *(tsonga)* ve *(venda)* xh *(xhosa)* yi *(yiddish)* zu *(zulu)*                                                                                                                                                                                         |
|zm         |Zambia                                    |en-zm *(english)*                                                                                                                                                                                                                                                                                                              |
|zw         |Zimbabwe                                  |en-zw *(english)* nd *(n. Ndebele)* sn *(shona)* ve *(venda)* zu *(zulu)*                                                                                                                                                                                                                                                              |
