### ISSUE TITLE
Licence for the actual equations?

### ISSUE THREAD

**Issue by andybak** [ai/easings.net#128]
Hi. I needed a set of easing equations for an MIT licenced Unity project. I grabbed these and ported them to C# before I spotted that this was GPL 3.0

I did a quick Github search and I can find several MIT licenced repos that have the same equations with the same names so I'm hoping that your copyright isn't on the actual formulae and names themselves.

I can redo the port from another source but I'd rather not - so I thought I'd check with you.

The project that makes use of them is here: https://github.com/IxxyXR/Polyhydra-upm

and the ported code is here: https://github.com/IxxyXR/polyhydra-upm/blob/master/Packages/Polyhydra/com.ixxy.polyhydra/Conway/Runtime/Easing.cs

Happy to add copyright/credits or anything you request - I just don't want to change my licence to GPL. I'd rather redo the port from another source if that's required.

**Comment by ai** [comment]
I copied formulas from jQuery, which uses MIT.

I am not sure that formulas are part of copyright. But even if they are part of copyright, you can thread them as MIT.

**Comment by andybak** [comment]
Cool. Thanks for that. It might be worth clarifying what parts of your code you think the GPL applies to. Otherwise it seems a bit like you've taken MIT code and released it under a more restrictive licence.

**Comment by JimmyCushnie** [comment]
I sure *hope* the equations aren't copyrighted or copyrightable. What a sad cynical thing it would be, to restrict the use of *math*.

**Comment by smolk0** [comment]
@andybak 
Hey,

Copyright law does not protect any particular idea. Rather, copyright protects only the expression of that idea.

So, do not worry about math equations, they are not subject of copyright protection=)

from [from https://www.copyright.gov/circs/circ31.pdf](https://www.copyright.gov/circs/circ31.pdf)
"Copyright law does not protect ideas, methods, or systems. Copyright protection is therefore not available for ideas or procedures for doing, making, or
building things; scientific or technical methods or discoveries; business operations or procedures; mathematical principles; formulas or algorithms; or any
other concept, process, or method of operation"

**Comment by gosolivs** [comment]
@smolk0 Thank you for your help!
