### ISSUE TITLE
Простите

### ISSUE THREAD

**Issue by acterhd** [ai/easings.net#46]
Убрано.

**Comment by ai** [comment]
Текст был сделан довольно давно, тогда для анимации использовался только jQuery.

Если мы заменим текст, то это убьёт всё переводы. Если бы текст действительно был важен, то так можно было бы поступить. Но главная цель сайта не рассказать об инструментах, а просто скопировать название функции в любой инструмент.

Я планирую через пару месяц (когда Сасс окончательно умрёт в пользу PostCSS) переписать текст про инструменты. Вот тогда и заменим.

**Comment by acterhd** [comment]
Поче
