### ISSUE TITLE
Examples for Less

### ISSUE THREAD

**Issue by var-bin** [ai/easings.net#57]
Hello!
Could you add an example for Less? I created [a repository](http://var-bin.github.io/less-easings/). This repository contains the variables that are generated based on your [project](https://github.com/ai/easings.net/blob/master/easings.yml) and an example for [Less](http://lesscss.org/).

**Comment by ai** [comment]
@var-bin Sorry, it will broke all translations. So I try to avoid content changes.

**Comment by var-bin** [comment]
What a pity! )
I like Less and would like to promote it

**Comment by ai** [comment]
@var-bin it is time to learn PostCSS :D. [postcss-easing](https://github.com/postcss/postcss-easings) looks like more CSSish.

I didn’t close this issue, because in some time I will update content.

**Comment by var-bin** [comment]
Yes, you are right.
I know about PostCSS and I used it. It is cool, but I like Less to.
