### ISSUE TITLE
Add examples for Android

### ISSUE THREAD

**Issue by dgmltn** [ai/easings.net#67]
It would be handy if easings.net gave an example for Android.

The bezier easing functions can be easily created in Android (as [Interpolator](https://developer.android.com/reference/android/view/animation/Interpolator.html)s) by using the [PathInterpolatorCompat](https://developer.android.com/reference/android/support/v4/view/animation/PathInterpolatorCompat.html) method here:

```
PathInterpolatorCompat.create(x1, y1, x2, y2)
```

**Comment by amylinn** [comment]
If this is added, it would be nice to convert the values to float.
They can then be easily used in Kotlin, too.

example:  

    //easeInOutQuart
    PathInterpolatorCompat.create(0.77f, 0f, 0.175f, 1f)

**Comment by ai** [comment]
I like this idea.

Main problem — it will kill all transactions. So I will do it on redesign later.
