### ISSUE TITLE
Hover problem

### ISSUE THREAD

**Issue by KirillPd** [ai/easings.net#70]
Hi! Thank you for this useful site.

I noticed an issue when you hover on "easeInQuad" function
![image](https://cloud.githubusercontent.com/assets/14921077/26547273/e275d696-4476-11e7-9956-8bb9cd05c50c.png)

Adding a z-index to ".part-title" solves this problem.

**Comment by ai** [comment]
Great. Do you want to send PR to save your name in project history?

But I will be able to accept and release it only after June 9.

**Comment by KirillPd** [comment]
It looks good now. Thanks!
