### ISSUE TITLE
Add Javascript equivalent function

### ISSUE THREAD

**Issue by VincentCharpentier** [ai/easings.net#74]
That would be nice to have the javascript function for each easing mode.

for instance:
```javascript
/**
* @param x input [0;1]
* @return eased input [0;1]
*/
function linear(x) {
  return x;
}
```
of course for thing like bounce effect ease value may leave the [0;1] range.

**Comment by ai** [comment]
Agree. I will add this idea for website refactoring (because it will kill translations).
