### ISSUE TITLE
Real-world examples for different curves

### ISSUE THREAD

**Issue by ujenjt** [ai/easings.net#91]
Hey, I really like the idea behind easings.net. Thanks for the website.

I have an idea that maybe would be useful for the project. It would be great to have a short list of real life examples for each curve.

For example for easeOutQuad curve the simplest example is animation for removing an item from the list. Like this:
https://stackoverflow.com/a/41223246/10558733
https://codepen.io/chriscoyier/pen/ozlJK

A list of links to examples hosted on codepen might works for this. 
What do you think?

**Comment by ujenjt** [comment]
@isolovev I am not sure about comprehensive list of examples but yes I can help with this. Also, maybe it's worth to iterate over the idea in wiki format first and once we get sufficient content you can move forward and create interface for this?

**Comment by isolovev** [comment]
I’m agree. I’ll do it
