### ISSUE TITLE
What are this?

### ISSUE THREAD

**Issue by hughanderson4** [ai/easings.net#93]
Is this JS?
Is this CSS?
How I use this?
What it is applicable to?
Example codes?

**Comment by ai** [comment]
> Is this JS? Is this CSS?

Easing functions are used in CSS and JS (and in many other programming languages for games and mobile development).

> How I use this? What it is applicable to? Example codes?

1. Go to website https://easings.net/
2. See the difference between different easing functions
3. Open a easing function (for instance, https://easings.net/en#easeInSine ). You will get code example how to use it in your app.
