### ISSUE TITLE
Easy function copy

### ISSUE THREAD

**Issue by MarcusCemes** [ai/easings.net#94]
Hi,

I use your page a lot as a reference for CSS easings, they add more feel to just about any UI animation.

I find myself selecting and copying the blue `cubic-beizer(...)` text a lot... There are awesome buttons to preview the easing for different animations, would it be possible to add a small button that copies the CSS easing function to your clipboard?

For those that don't like installing CSS plugins that transform easings automatically, this website is godsent.

**Comment by isolovev** [comment]
Hey. It is a good idea. In any time soon will make this!

**Comment by josias-r** [comment]
Why not simply generate an SCSS file containing all the easing functions as SCSS variables?
Example: `$easeOutQuad: cubic-bezier(0.25, 0.46, 0.45, 0.94);`

**Comment by isolovev** [comment]
Hey. There are ready files.
https://github.com/KingScooty/sass-easing

**Comment by MarcusCemes** [comment]
@josias-r That is a quick-fix solution for a particular situation. SCSS is not supported by any browser and requires an specialized compiler during the build process. Not everyone uses it. Of course, there are SCSS, LESS, VS Code, ..., extensions that offer snippets/compile-time replacements.

I created this issue however as an enhancement for an extremely useful quick-reference website that allows you to visualize and compare easings.

**Comment by josias-r** [comment]
@MarcusCemes I agree, I just thought it's related to your issue because when working on an opened project and you want to compare different easings it would be way easier if you could just change the variable name instead of having to open the website at all...

@isolovev you are referring to a different repo?

**Comment by isolovev** [comment]
Yeah, I meant another repo. Not everyone uses SCSS. I don't see any point in implementing an already made file or tool that copes with its task.
