### ISSUE TITLE
Select option for light and dark mode

### ISSUE THREAD

**Issue by elebumm** [ai/easings.net#95]
Use this site almost daily. Love it guys. 

I might be in the minority here... but I like light themes more than dark themes. I saw that the site switched over to a dark theme. I could possibly work on this feature, but would it make sense to add a lightbulb or something at the bottom of the page to toggle between each?

**Comment by ai** [comment]
If we will add switcher it should have 3 values: light, auto, dark.

But do we have any good reason for a manual switcher over the `prefers-color-scheme` media query and using OS settings?
