### ISSUE TITLE
Only 2 languages in menu

### ISSUE THREAD

**Issue by debugDS** [ai/easings.net#96]
Hi guys great site!
Event if languages are present in i18n folder they don't appear in menu.
For example, /fr cause 404

Thanks

**Comment by isolovev** [comment]
Hello! Files prefixed with `_` are not displayed on the site.

**Comment by th0rgall** [comment]
Hey @isolovev, why not remove the prefixes then? Do you only want English/Russian translations to be visible on the site?

**Comment by isolovev** [comment]
Hello @th0rgall . I had to add new translation keys and remove some old ones. Therefore, I added a prefix to the files so that people who want to translate had something to start from.

**Comment by th0rgall** [comment]
@isolovev oh I see, that makes sense. I'll try to help with the Dutch translation then. I like the way you invited people to help with translations 👍

**Comment by isolovev** [comment]
@th0rgall thank you! Let's make a better tool! 👍
