### ISSUE TITLE
Broken chart animation in Safari

### ISSUE THREAD

**Issue by AlisaLiso** [ai/easings.net#98]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33451920/66410990-b38df980-e9fb-11e9-99ea-5acf47c490bb.gif)

I found a bug in Safari(Version 13.0.2) when active animation on the third item of the charts group isn't working. 

The problem is that 'will-change' should optimize the opacity animation and it does break somehow animation in Safari. I have changed styles from `will-change: top, opacity;` to `will-change: top;` to get it fixed. 

This issue happens only in Safari so far.

Link to the file.
https://github.com/ai/easings.net/blob/master/src/chart/chart.css#L74

**Comment by isolovev** [comment]
Hello. Thank you for finding the bug!
